export const FETCHING_STATRT = 'FETCHING_STATRT';
export const WEATHER_FETCHED = 'WEATHER_FETCHED';
export const LOCATION_DATA_FETCHED = 'LOCATION_DATA_FETCHED';
export const ERROR_FETCHED = 'ERROR_FETCHED';
